kind: Ingress
metadata:
  name: papi-ingress
  namespace: zockets
  annotations:
    kubernetes.io/ingress.class: "nginx" # Specifies the Ingress class for the NGINX Ingress Controller
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
